// NOUVELLE STRUCTURE DE DONNÉES - À AJOUTER
// Cette structure de données est la nouvelle source de vérité pour les relations entre Sourate, Juzz et Hizb.
// Elle est plus simple et plus robuste que les anciennes méthodes basées sur les pages.

export interface SurahMetadata {
  numero: number;
  nom: string;
  juz: number;
  hizb: number;
}

export const QURAN_METADATA: SurahMetadata[] = [
  { "numero": 1, "nom": "Al-Fatiha", "juz": 1, "hizb": 1 },
  { "numero": 2, "nom": "Al-Baqara", "juz": 1, "hizb": 1 }, // Note: Cette sourate s'étend sur plusieurs Juzz/Hizb, ici c'est son point de départ.
  { "numero": 3, "nom": "Al-Imran", "juz": 3, "hizb": 5 },
  { "numero": 4, "nom": "An-Nisa", "juz": 4, "hizb": 7 },
  { "numero": 5, "nom": "Al-Ma'idah", "juz": 6, "hizb": 10 },
  { "numero": 6, "nom": "Al-An'am", "juz": 7, "hizb": 12 },
  { "numero": 7, "nom": "Al-A'raf", "juz": 8, "hizb": 13 },
  { "numero": 8, "nom": "Al-Anfal", "juz": 9, "hizb": 15 },
  { "numero": 9, "nom": "At-Tawbah", "juz": 10, "hizb": 17 },
  { "numero": 10, "nom": "Yunus", "juz": 11, "hizb": 21 },
  { "numero": 11, "nom": "Hud", "juz": 11, "hizb": 21 },
  { "numero": 12, "nom": "Yusuf", "juz": 12, "hizb": 24 },
  { "numero": 13, "nom": "Ar-Ra'd", "juz": 13, "hizb": 25 },
  { "numero": 14, "nom": "Ibrahim", "juz": 13, "hizb": 26 },
  { "numero": 15, "nom": "Al-Hijr", "juz": 14, "hizb": 27 },
  { "numero": 16, "nom": "An-Nahl", "juz": 14, "hizb": 27 },
  { "numero": 17, "nom": "Al-Isra", "juz": 15, "hizb": 29 },
  { "numero": 18, "nom": "Al-Kahf", "juz": 15, "hizb": 30 },
  { "numero": 19, "nom": "Maryam", "juz": 16, "hizb": 32 },
  { "numero": 20, "nom": "Taha", "juz": 16, "hizb": 32 },
  { "numero": 21, "nom": "Al-Anbiya", "juz": 17, "hizb": 34 },
  { "numero": 22, "nom": "Al-Hajj", "juz": 17, "hizb": 35 },
  { "numero": 23, "nom": "Al-Mu'minun", "juz": 18, "hizb": 36 },
  { "numero": 24, "nom": "An-Nur", "juz": 18, "hizb": 37 },
  { "numero": 25, "nom": "Al-Furqan", "juz": 19, "hizb": 38 },
  { "numero": 26, "nom": "Ash-Shu'ara", "juz": 19, "hizb": 39 },
  { "numero": 27, "nom": "An-Naml", "juz": 19, "hizb": 40 },
  { "numero": 28, "nom": "Al-Qasas", "juz": 20, "hizb": 41 },
  { "numero": 29, "nom": "Al-Ankabut", "juz": 20, "hizb": 42 },
  { "numero": 30, "nom": "Ar-Rum", "juz": 21, "hizb": 43 },
  { "numero": 31, "nom": "Luqman", "juz": 21, "hizb": 43 },
  { "numero": 32, "nom": "As-Sajda", "juz": 21, "hizb": 44 },
  { "numero": 33, "nom": "Al-Ahzab", "juz": 21, "hizb": 43 },
  { "numero": 34, "nom": "Saba", "juz": 22, "hizb": 45 },
  { "numero": 35, "nom": "Fatir", "juz": 22, "hizb": 45 },
  { "numero": 36, "nom": "Ya-Sin", "juz": 22, "hizb": 46 },
  { "numero": 37, "nom": "As-Saffat", "juz": 23, "hizb": 47 },
  { "numero": 38, "nom": "Sad", "juz": 23, "hizb": 47 },
  { "numero": 39, "nom": "Az-Zumar", "juz": 23, "hizb": 48 },
  { "numero": 40, "nom": "Ghafir", "juz": 24, "hizb": 48 },
  { "numero": 41, "nom": "Fussilat", "juz": 24, "hizb": 49 },
  { "numero": 42, "nom": "Ash-Shura", "juz": 25, "hizb": 50 },
  { "numero": 43, "nom": "Az-Zukhruf", "juz": 25, "hizb": 50 },
  { "numero": 44, "nom": "Ad-Dukhan", "juz": 25, "hizb": 51 },
  { "numero": 45, "nom": "Al-Jathiyah", "juz": 25, "hizb": 51 },
  { "numero": 46, "nom": "Al-Ahqaf", "juz": 26, "hizb": 52 },
  { "numero": 47, "nom": "Muhammad", "juz": 26, "hizb": 52 },
  { "numero": 48, "nom": "Al-Fath", "juz": 26, "hizb": 53 },
  { "numero": 49, "nom": "Al-Hujurat", "juz": 26, "hizb": 53 },
  { "numero": 50, "nom": "Qaf", "juz": 26, "hizb": 53 },
  { "numero": 51, "nom": "Adh-Dhariyat", "juz": 27, "hizb": 54 },
  { "numero": 52, "nom": "At-Tur", "juz": 27, "hizb": 54 },
  { "numero": 53, "nom": "An-Najm", "juz": 27, "hizb": 54 },
  { "numero": 54, "nom": "Al-Qamar", "juz": 27, "hizb": 55 },
  { "numero": 55, "nom": "Ar-Rahman", "juz": 27, "hizb": 55 },
  { "numero": 56, "nom": "Al-Waqi'ah", "juz": 27, "hizb": 55 },
  { "numero": 57, "nom": "Al-Hadid", "juz": 27, "hizb": 56 },
  { "numero": 58, "nom": "Al-Mujadila", "juz": 28, "hizb": 56 },
  { "numero": 59, "nom": "Al-Hashr", "juz": 28, "hizb": 56 },
  { "numero": 60, "nom": "Al-Mumtahanah", "juz": 28, "hizb": 57 },
  { "numero": 61, "nom": "As-Saff", "juz": 28, "hizb": 57 },
  { "numero": 62, "nom": "Al-Jumu'ah", "juz": 28, "hizb": 57 },
  { "numero": 63, "nom": "Al-Munafiqun", "juz": 28, "hizb": 57 },
  { "numero": 64, "nom": "At-Taghabun", "juz": 28, "hizb": 58 },
  { "numero": 65, "nom": "At-Talaq", "juz": 28, "hizb": 58 },
  { "numero": 66, "nom": "At-Tahrim", "juz": 28, "hizb": 58 },
  { "numero": 67, "nom": "Al-Mulk", "juz": 29, "hizb": 58 },
  { "numero": 68, "nom": "Al-Qalam", "juz": 29, "hizb": 58 },
  { "numero": 69, "nom": "Al-Haqqah", "juz": 29, "hizb": 59 },
  { "numero": 70, "nom": "Al-Ma'arij", "juz": 29, "hizb": 59 },
  { "numero": 71, "nom": "Nuh", "juz": 29, "hizb": 59 },
  { "numero": 72, "nom": "Al-Jinn", "juz": 29, "hizb": 59 },
  { "numero": 73, "nom": "Al-Muzzammil", "juz": 29, "hizb": 59 },
  { "numero": 74, "nom": "Al-Muddaththir", "juz": 29, "hizb": 59 },
  { "numero": 75, "nom": "Al-Qiyamah", "juz": 29, "hizb": 59 },
  { "numero": 76, "nom": "Al-Insan", "juz": 29, "hizb": 59 },
  { "numero": 77, "nom": "Al-Mursalat", "juz": 29, "hizb": 60 },
  { "numero": 78, "nom": "An-Naba", "juz": 30, "hizb": 60 },
  { "numero": 79, "nom": "An-Nazi'at", "juz": 30, "hizb": 60 },
  { "numero": 80, "nom": "Abasa", "juz": 30, "hizb": 60 },
  { "numero": 81, "nom": "At-Takwir", "juz": 30, "hizb": 60 },
  { "numero": 82, "nom": "Al-Infitar", "juz": 30, "hizb": 60 },
  { "numero": 83, "nom": "Al-Mutaffifin", "juz": 30, "hizb": 60 },
  { "numero": 84, "nom": "Al-Inshiqaq", "juz": 30, "hizb": 60 },
  { "numero": 85, "nom": "Al-Buruj", "juz": 30, "hizb": 60 },
  { "numero": 86, "nom": "At-Tariq", "juz": 30, "hizb": 60 },
  { "numero": 87, "nom": "Al-A'la", "juz": 30, "hizb": 60 },
  { "numero": 88, "nom": "Al-Ghashiyah", "juz": 30, "hizb": 60 },
  { "numero": 89, "nom": "Al-Fajr", "juz": 30, "hizb": 60 },
  { "numero": 90, "nom": "Al-Balad", "juz": 30, "hizb": 60 },
  { "numero": 91, "nom": "Ash-Shams", "juz": 30, "hizb": 60 },
  { "numero": 92, "nom": "Al-Lail", "juz": 30, "hizb": 60 },
  { "numero": 93, "nom": "Ad-Duhaa", "juz": 30, "hizb": 60 },
  { "numero": 94, "nom": "Ash-Sharh", "juz": 30, "hizb": 60 },
  { "numero": 95, "nom": "At-Tin", "juz": 30, "hizb": 60 },
  { "numero": 96, "nom": "Al-Alaq", "juz": 30, "hizb": 60 },
  { "numero": 97, "nom": "Al-Qadr", "juz": 30, "hizb": 60 },
  { "numero": 98, "nom": "Al-Bayyinah", "juz": 30, "hizb": 60 },
  { "numero": 99, "nom": "Az-Zalzalah", "juz": 30, "hizb": 60 },
  { "numero": 100, "nom": "Al-Adiyat", "juz": 30, "hizb": 60 },
  { "numero": 101, "nom": "Al-Qari'ah", "juz": 30, "hizb": 60 },
  { "numero": 102, "nom": "At-Takathur", "juz": 30, "hizb": 60 },
  { "numero": 103, "nom": "Al-Asr", "juz": 30, "hizb": 60 },
  { "numero": 104, "nom": "Al-Humazah", "juz": 30, "hizb": 60 },
  { "numero": 105, "nom": "Al-Fil", "juz": 30, "hizb": 60 },
  { "numero": 106, "nom": "Quraish", "juz": 30, "hizb": 60 },
  { "numero": 107, "nom": "Al-Ma'un", "juz": 30, "hizb": 60 },
  { "numero": 108, "nom": "Al-Kawthar", "juz": 30, "hizb": 60 },
  { "numero": 109, "nom": "Al-Kafirun", "juz": 30, "hizb": 60 },
  { "numero": 110, "nom": "An-Nasr", "juz": 30, "hizb": 60 },
  { "numero": 111, "nom": "Al-Masad", "juz": 30, "hizb": 60 },
  { "numero": 112, "nom": "Al-Ikhlas", "juz": 30, "hizb": 60 },
  { "numero": 113, "nom": "Al-Falaq", "juz": 30, "hizb": 60 },
  { "numero": 114, "nom": "An-Nas", "juz": 30, "hizb": 60 }
];